### ISSUE TITLE
csfloat extension is not working 

### ISSUE THREAD

**Issue by GrexVibra** [csfloat/extension#261] opened 2024-10-06 10:55 UTC
stuck on loading.
![Capture](https://github.com/user-attachments/assets/442daf04-1c78-4950-abe6-42f5f0f0715f)

tried uninstall/install both extension and firefox multiple times, still same.
w10, firefox updated.
kindly help

**Comment by Step7750** [comment] 2024-10-20 19:44
Duplicate of #258

**Closed by Step7750** 2024-10-20 19:44 UTC
